version : "3"
services:
  web:
    build:
      context: .
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 7777:3306